// -----------------------------------------------------------------------------
//	s2026_cpu_controller.v
//	  CPU selector wrapper for Z80/R800
// -----------------------------------------------------------------------------

module s2026_cpu_controller (
	input			reset_n,
	input			clk,
	input			enable_z80,
	input			enable_r800,
	input			cpu_pause,
	input			cpu_change_req,
	input			cpu_change_target,
	input			z80_m1,
	input			z80_mreq,
	input			z80_iorq,
	input			z80_rd,
	input			z80_wr,
	input	[15:0]	z80_a,
	input	[7:0]	z80_wdata,
	output	[7:0]	z80_rdata,
	input			r800_m1,
	input			r800_mreq,
	input			r800_iorq,
	input			r800_rd,
	input			r800_wr,
	input	[15:0]	r800_a,
	input	[7:0]	r800_wdata,
	output	[7:0]	r800_rdata,
	output			bus_m1,
	output			bus_io,
	output			bus_write,
	output			bus_valid,
	input			bus_ready,
	output	[7:0]	bus_wdata,
	output	[15:0]	bus_address,
	input	[7:0]	bus_rdata,
	input			bus_rdata_en,
	output			z80_active,
	output			r800_active,
	output			processor_mode
);
	wire			w_bus_mem;

	s2026_cpu_select u_cpu_select (
		.reset_n			( reset_n			),
		.clk				( clk				),
		.enable_z80			( enable_z80		),
		.enable_r800		( enable_r800		),
		.z80_m1				( z80_m1			),
		.z80_mreq			( z80_mreq			),
		.z80_iorq			( z80_iorq			),
		.z80_rd				( z80_rd			),
		.z80_wr				( z80_wr			),
		.z80_a				( z80_a				),
		.z80_wdata			( z80_wdata		),
		.z80_rdata			( z80_rdata		),
		.r800_m1			( r800_m1			),
		.r800_mreq			( r800_mreq		),
		.r800_iorq			( r800_iorq		),
		.r800_rd			( r800_rd			),
		.r800_wr			( r800_wr			),
		.r800_a				( r800_a			),
		.r800_wdata			( r800_wdata		),
		.r800_rdata			( r800_rdata		),
		.cpu_change_req		( cpu_change_req	),
		.cpu_change_target	( cpu_change_target	),
		.cpu_pause			( cpu_pause		),
		.rdata				( bus_rdata		),
		.rdata_en			( bus_rdata_en		),
		.z80_active			( z80_active		),
		.r800_active		( r800_active		),
		.processor_mode		( processor_mode	),
		.address			( bus_address		),
		.bus_m1				( bus_m1			),
		.bus_io				( bus_io			),
		.bus_mem			( w_bus_mem		),
		.bus_write			( bus_write		),
		.bus_valid			( bus_valid		),
		.bus_wdata			( bus_wdata		),
		.bus_ready			( bus_ready		)
	);
endmodule